# Generated by Django 2.1.5 on 2021-06-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sells',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
