# Generated by Django 2.1.5 on 2021-06-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_stock_sells'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='sells',
            new_name='sales',
        ),
    ]
