# Generated by Django 2.1.5 on 2021-06-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0004_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.CharField(blank=True, max_length=60, primary_key=True, serialize=False),
        ),
    ]
