# Generated by Django 2.1.5 on 2021-06-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0005_auto_20210627_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='id_sale',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
